# Generated by Django 2.2.4 on 2019-08-02 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0002_bucketlist_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucketlist',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='buketlists', to=settings.AUTH_USER_MODEL),
        ),
    ]
