# Generated by Django 2.2.3 on 2019-07-25 13:48

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllFeilds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(choices=[('pune', 'Pune'), ('mumbai', 'Mumbai'), ('nashik', 'Nashik')], max_length=50)),
                ('my_field', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'C'), (2, 'C++'), (3, 'Python'), (4, 'Django'), (5, 'JavaScript')], max_length=9)),
            ],
        ),
    ]
