# Generated by Django 2.2.3 on 2019-07-25 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AllFeilds',
            new_name='AllFeilds_1',
        ),
    ]
