# Generated by Django 2.2.3 on 2019-07-25 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20190725_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allfeilds_1',
            name='city',
        ),
        migrations.RemoveField(
            model_name='allfeilds_1',
            name='my_field',
        ),
    ]
