# Generated by Django 2.2.3 on 2019-07-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_auto_20190725_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='allfeilds_1',
            name='city',
            field=models.CharField(choices=[('pune', 'Pune'), ('mumbai', 'Mumbai'), ('nashik', 'Nashik')], default='', max_length=50),
            preserve_default=False,
        ),
    ]
