# Generated by Django 2.2.3 on 2019-07-25 13:58

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_allfeilds_1_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='allfeilds_1',
            name='languages',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'C'), (2, 'C++'), (3, 'Python'), (4, 'Django'), (5, 'JavaScript')], default='', max_length=9),
            preserve_default=False,
        ),
    ]
