# Generated by Django 2.2.3 on 2019-07-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_allfeilds_1_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='allfeilds_1',
            name='upload',
            field=models.FileField(default='', upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
