# Generated by Django 2.2.3 on 2019-07-26 09:31

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_allfeilds_1_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('degnation', models.CharField(max_length=20)),
                ('mobile', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('dop', models.DateField(default=True)),
                ('city', models.CharField(choices=[('pune', 'Pune'), ('mumbai', 'Mumbai'), ('nashik', 'Nashik')], max_length=50)),
                ('languages', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'C'), (2, 'C++'), (3, 'Python'), (4, 'Django'), (5, 'JavaScript')], max_length=9)),
                ('upload', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
