# Generated by Django 2.2.3 on 2019-07-28 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0007_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='allfeilds_1',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='allfeilds_1',
            name='web',
            field=models.URLField(default='', verbose_name='Web Address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='allfeilds_1',
            name='upload',
            field=models.FileField(default='', upload_to='uploads/'),
        ),
    ]
