# Generated by Django 2.2.3 on 2019-07-29 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0008_auto_20190728_1610'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.AddField(
            model_name='allfeilds_1',
            name='gender',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
