# Generated by Django 2.2.3 on 2019-07-29 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0009_auto_20190729_0705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allfeilds_1',
            name='gender',
        ),
    ]
