# Generated by Django 2.2.3 on 2019-07-29 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0010_remove_allfeilds_1_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='allfeilds_1',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='', max_length=20),
            preserve_default=False,
        ),
    ]
